export const NavbarData = [
    {
        id:1,
        label:"Dashboard", 
        path:"/"},
    {
        id:2,
        label:"Incidents", 
        path:"/incidents"
    },
    {
        id:3,
        label:"Locations", 
        path:"/locations"
    },
    {
        id:4,
        label:"Activities", 
        path:"/activities"
    },
    {
        id:5,
        label:"Documents", 
        path:"/documents"
    },
    {
        id:6,
        label:"CypherAi", 
        path:"/cypherai"
    },
]